// Registration Actions
export const USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS";
export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";
export const USER_REGISTRATION_FAILED = "USER_REGISTRATION_FAILED";
export const USER_REGISTRATION_PROGRESS = "USER_REGISTRATION_PROGRESS";
export const USER_REGISTRATION_DEFAULT = "USER_REGISTRATION_DEFAULT";
export const PASSPORT_UPLOAD_SUCCESS = "PASSPORT_UPLOAD_SUCCESS";
export const PASSPORT_UPLOAD_FAILED = "PASSPORT_UPLOAD_FAILED";
export const POLICE_REPORT_UPLOAD_SUCCESS = "POLICE_REPORT_UPLOAD_SUCCESS";
export const POLICE_REPORT_UPLOAD_FAILED = "POLICE_REPORT_UPLOAD_FAILED";
export const USER_REGISTRATION_COMPLETED = "USER_REGISTRATION_COMPLETED";

// Auth Actions
export const SET_USER = 'SET_USER';
export const SIGN_OUT = 'SIGN_OUT';
export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';
export const SET_SUCCESS = 'SET_SUCCESS';

// TABLES
export const ADMIN_TABLE_DATA = "ADMIN_TABLE_DATA";
export const EMPLOYEE_TABLE_DATA = "EMPLOYEE_TABLE_DATA";
export const SCHEDULED_JOB_TABLE_DATA = "SCHEDULED_JOB_TABLE_DATA";

// Job Scheduling
export const EMPLOYEE_EMAILS = "EMPLOYEE_EMAILS";
export const SCHEDULE_JOB_SUCCESS = "SCHEDULE_JOB_SUCCESS";
export const SCHEDULE_JOB_FAILED = "SCHEDULE_JOB_FAILED";
export const SCHEDULE_JOB_TITLE_ALREADY_EXISTS = "SCHEDULE_JOB_TITLE_ALREADY_EXISTS";
export const SCHEDULE_JOB_DEFAULT = "SCHEDULE_JOB_DEFAULT";

// Other
export const ERROR = "ERROR";
